// Datos completos para NihongoApp
// Aprende Japonés Completo

const NihongoData = {
    // Silabarios completos
    silabarios: {
        hiragana: [
            { character: 'あ', romaji: 'a', reading: 'a' },
            { character: 'い', romaji: 'i', reading: 'i' },
            { character: 'う', romaji: 'u', reading: 'u' },
            { character: 'え', romaji: 'e', reading: 'e' },
            { character: 'お', romaji: 'o', reading: 'o' },
            { character: 'か', romaji: 'ka', reading: 'ka' },
            { character: 'き', romaji: 'ki', reading: 'ki' },
            { character: 'く', romaji: 'ku', reading: 'ku' },
            { character: 'け', romaji: 'ke', reading: 'ke' },
            { character: 'こ', romaji: 'ko', reading: 'ko' },
            { character: 'が', romaji: 'ga', reading: 'ga' },
            { character: 'ぎ', romaji: 'gi', reading: 'gi' },
            { character: 'ぐ', romaji: 'gu', reading: 'gu' },
            { character: 'げ', romaji: 'ge', reading: 'ge' },
            { character: 'ご', romaji: 'go', reading: 'go' },
            { character: 'さ', romaji: 'sa', reading: 'sa' },
            { character: 'し', romaji: 'shi', reading: 'shi' },
            { character: 'す', romaji: 'su', reading: 'su' },
            { character: 'せ', romaji: 'se', reading: 'se' },
            { character: 'そ', romaji: 'so', reading: 'so' },
            { character: 'ざ', romaji: 'za', reading: 'za' },
            { character: 'じ', romaji: 'ji', reading: 'ji' },
            { character: 'ず', romaji: 'zu', reading: 'zu' },
            { character: 'ぜ', romaji: 'ze', reading: 'ze' },
            { character: 'ぞ', romaji: 'zo', reading: 'zo' },
            { character: 'た', romaji: 'ta', reading: 'ta' },
            { character: 'ち', romaji: 'chi', reading: 'chi' },
            { character: 'つ', romaji: 'tsu', reading: 'tsu' },
            { character: 'て', romaji: 'te', reading: 'te' },
            { character: 'と', romaji: 'to', reading: 'to' },
            { character: 'だ', romaji: 'da', reading: 'da' },
            { character: 'ぢ', romaji: 'di', reading: 'di' },
            { character: 'づ', romaji: 'du', reading: 'du' },
            { character: 'で', romaji: 'de', reading: 'de' },
            { character: 'ど', romaji: 'do', reading: 'do' },
            { character: 'な', romaji: 'na', reading: 'na' },
            { character: 'に', romaji: 'ni', reading: 'ni' },
            { character: 'ぬ', romaji: 'nu', reading: 'nu' },
            { character: 'ね', romaji: 'ne', reading: 'ne' },
            { character: 'の', romaji: 'no', reading: 'no' },
            { character: 'は', romaji: 'ha', reading: 'ha' },
            { character: 'ひ', romaji: 'hi', reading: 'hi' },
            { character: 'ふ', romaji: 'fu', reading: 'fu' },
            { character: 'へ', romaji: 'he', reading: 'he' },
            { character: 'ほ', romaji: 'ho', reading: 'ho' },
            { character: 'ば', romaji: 'ba', reading: 'ba' },
            { character: 'び', romaji: 'bi', reading: 'bi' },
            { character: 'ぶ', romaji: 'bu', reading: 'bu' },
            { character: 'べ', romaji: 'be', reading: 'be' },
            { character: 'ぼ', romaji: 'bo', reading: 'bo' },
            { character: 'ぱ', romaji: 'pa', reading: 'pa' },
            { character: 'ぴ', romaji: 'pi', reading: 'pi' },
            { character: 'ぷ', romaji: 'pu', reading: 'pu' },
            { character: 'ぺ', romaji: 'pe', reading: 'pe' },
            { character: 'ぽ', romaji: 'po', reading: 'po' },
            { character: 'ま', romaji: 'ma', reading: 'ma' },
            { character: 'み', romaji: 'mi', reading: 'mi' },
            { character: 'む', romaji: 'mu', reading: 'mu' },
            { character: 'め', romaji: 'me', reading: 'me' },
            { character: 'も', romaji: 'mo', reading: 'mo' },
            { character: 'や', romaji: 'ya', reading: 'ya' },
            { character: 'ゆ', romaji: 'yu', reading: 'yu' },
            { character: 'よ', romaji: 'yo', reading: 'yo' },
            { character: 'ら', romaji: 'ra', reading: 'ra' },
            { character: 'り', romaji: 'ri', reading: 'ri' },
            { character: 'る', romaji: 'ru', reading: 'ru' },
            { character: 'れ', romaji: 're', reading: 're' },
            { character: 'ろ', romaji: 'ro', reading: 'ro' },
            { character: 'わ', romaji: 'wa', reading: 'wa' },
            { character: 'ゐ', romaji: 'wi', reading: 'wi' },
            { character: 'ゑ', romaji: 'we', reading: 'we' },
            { character: 'を', romaji: 'wo', reading: 'wo' },
            { character: 'ん', romaji: 'n', reading: 'n' }
        ],
        
        katakana: [
            { character: 'ア', romaji: 'a', reading: 'a' },
            { character: 'イ', romaji: 'i', reading: 'i' },
            { character: 'ウ', romaji: 'u', reading: 'u' },
            { character: 'エ', romaji: 'e', reading: 'e' },
            { character: 'オ', romaji: 'o', reading: 'o' },
            { character: 'カ', romaji: 'ka', reading: 'ka' },
            { character: 'キ', romaji: 'ki', reading: 'ki' },
            { character: 'ク', romaji: 'ku', reading: 'ku' },
            { character: 'ケ', romaji: 'ke', reading: 'ke' },
            { character: 'コ', romaji: 'ko', reading: 'ko' },
            { character: 'ガ', romaji: 'ga', reading: 'ga' },
            { character: 'ギ', romaji: 'gi', reading: 'gi' },
            { character: 'グ', romaji: 'gu', reading: 'gu' },
            { character: 'ゲ', romaji: 'ge', reading: 'ge' },
            { character: 'ゴ', romaji: 'go', reading: 'go' },
            { character: 'サ', romaji: 'sa', reading: 'sa' },
            { character: 'シ', romaji: 'shi', reading: 'shi' },
            { character: 'ス', romaji: 'su', reading: 'su' },
            { character: 'セ', romaji: 'se', reading: 'se' },
            { character: 'ソ', romaji: 'so', reading: 'so' },
            { character: 'ザ', romaji: 'za', reading: 'za' },
            { character: 'ジ', romaji: 'ji', reading: 'ji' },
            { character: 'ズ', romaji: 'zu', reading: 'zu' },
            { character: 'ゼ', romaji: 'ze', reading: 'ze' },
            { character: 'ゾ', romaji: 'zo', reading: 'zo' },
            { character: 'タ', romaji: 'ta', reading: 'ta' },
            { character: 'チ', romaji: 'chi', reading: 'chi' },
            { character: 'ツ', romaji: 'tsu', reading: 'tsu' },
            { character: 'テ', romaji: 'te', reading: 'te' },
            { character: 'ト', romaji: 'to', reading: 'to' },
            { character: 'ダ', romaji: 'da', reading: 'da' },
            { character: 'ヂ', romaji: 'di', reading: 'di' },
            { character: 'ヅ', romaji: 'du', reading: 'du' },
            { character: 'デ', romaji: 'de', reading: 'de' },
            { character: 'ド', romaji: 'do', reading: 'do' },
            { character: 'ナ', romaji: 'na', reading: 'na' },
            { character: 'ニ', romaji: 'ni', reading: 'ni' },
            { character: 'ヌ', romaji: 'nu', reading: 'nu' },
            { character: 'ネ', romaji: 'ne', reading: 'ne' },
            { character: 'ノ', romaji: 'no', reading: 'no' },
            { character: 'ハ', romaji: 'ha', reading: 'ha' },
            { character: 'ヒ', romaji: 'hi', reading: 'hi' },
            { character: 'フ', romaji: 'fu', reading: 'fu' },
            { character: 'ヘ', romaji: 'he', reading: 'he' },
            { character: 'ホ', romaji: 'ho', reading: 'ho' },
            { character: 'バ', romaji: 'ba', reading: 'ba' },
            { character: 'ビ', romaji: 'bi', reading: 'bi' },
            { character: 'ブ', romaji: 'bu', reading: 'bu' },
            { character: 'ベ', romaji: 'be', reading: 'be' },
            { character: 'ボ', romaji: 'bo', reading: 'bo' },
            { character: 'パ', romaji: 'pa', reading: 'pa' },
            { character: 'ピ', romaji: 'pi', reading: 'pi' },
            { character: 'プ', romaji: 'pu', reading: 'pu' },
            { character: 'ペ', romaji: 'pe', reading: 'pe' },
            { character: 'ポ', romaji: 'po', reading: 'po' },
            { character: 'マ', romaji: 'ma', reading: 'ma' },
            { character: 'ミ', romaji: 'mi', reading: 'mi' },
            { character: 'ム', romaji: 'mu', reading: 'mu' },
            { character: 'メ', romaji: 'me', reading: 'me' },
            { character: 'モ', romaji: 'mo', reading: 'mo' },
            { character: 'ヤ', romaji: 'ya', reading: 'ya' },
            { character: 'ユ', romaji: 'yu', reading: 'yu' },
            { character: 'ヨ', romaji: 'yo', reading: 'yo' },
            { character: 'ラ', romaji: 'ra', reading: 'ra' },
            { character: 'リ', romaji: 'ri', reading: 'ri' },
            { character: 'ル', romaji: 'ru', reading: 'ru' },
            { character: 'レ', romaji: 're', reading: 're' },
            { character: 'ロ', romaji: 'ro', reading: 'ro' },
            { character: 'ワ', romaji: 'wa', reading: 'wa' },
            { character: 'ヰ', romaji: 'wi', reading: 'wi' },
            { character: 'ヱ', romaji: 'we', reading: 'we' },
            { character: 'ヲ', romaji: 'wo', reading: 'wo' },
            { character: 'ン', romaji: 'n', reading: 'n' }
        ]
    },

    // Vocabulario Español
    vocabularioEsp: [
        { japanese: 'こんにちは', romaji: 'konnichiwa', spanish: 'hola', type: 'saludo' },
        { japanese: 'ありがとう', romaji: 'arigatou', spanish: 'gracias', type: 'agradecimiento' },
        { japanese: 'すみません', romaji: 'sumimasen', spanish: 'disculpa', type: 'disculpa' },
        { japanese: 'さようなら', romaji: 'sayounara', spanish: 'adiós', type: 'despedida' },
        { japanese: 'おはよう', romaji: 'ohayou', spanish: 'buenos días', type: 'saludo' },
        { japanese: 'こんばんは', romaji: 'kombanwa', spanish: 'buenas tardes', type: 'saludo' },
        { japanese: 'おやすみ', romaji: 'oyasumi', spanish: 'buenas noches', type: 'saludo' },
        { japanese: 'はじめまして', romaji: 'hajimemashite', spanish: 'encantado', type: 'presentación' },
        { japanese: 'わかりました', romaji: 'wakarimashita', spanish: 'entendí', type: 'comprensión' },
        { japanese: 'わからない', romaji: 'wakaranai', spanish: 'no entiendo', type: 'comprensión' },
        { japanese: 'だいじょうぶ', romaji: 'daijoubu', spanish: 'está bien', type: 'estado' },
        { japanese: 'げんき', romaji: 'genki', spanish: 'animado/saludable', type: 'estado' },
        { japanese: 'いま', romaji: 'ima', spanish: 'ahora', type: 'tiempo' },
        { japanese: 'あとで', romaji: 'atode', spanish: 'después', type: 'tiempo' },
        { japanese: 'あした', romaji: 'ashita', spanish: 'mañana', type: 'tiempo' },
        { japanese: 'きょう', romaji: 'kyou', spanish: 'hoy', type: 'tiempo' }
    ],

    // Vocabulario Japonés
    vocabularioJap: [
        { kanji: '学生', hiragana: 'がくせい', romaji: 'gakusei', spanish: 'estudiante', jlpt: 'N5' },
        { kanji: '先生', hiragana: 'せんせい', romaji: 'sensei', spanish: 'profesor', jlpt: 'N5' },
        { kanji: '学校', hiragana: 'がっこう', romaji: 'gakkou', spanish: 'escuela', jlpt: 'N5' },
        { kanji: '友達', hiragana: 'ともだち', romaji: 'tomodachi', spanish: 'amigos', jlpt: 'N5' },
        { kanji: '家族', hiragana: 'かぞく', romaji: 'kazoku', spanish: 'familia', jlpt: 'N4' },
        { kanji: '時間', hiragana: 'じかん', romaji: 'jikan', spanish: 'tiempo/hora', jlpt: 'N5' },
        { kanji: '朝ごはん', hiragana: 'あさごはん', romaji: 'asagohan', spanish: 'desayuno', jlpt: 'N4' },
        { kanji: '昼ごはん', hiragana: 'ひるごはん', romaji: 'hirugohan', spanish: 'almuerzo', jlpt: 'N3' },
        { kanji: '晩ごはん', hiragana: 'ばんごはん', romaji: 'bangohan', spanish: 'cena', jlpt: 'N3' },
        { kanji: '水', hiragana: 'みず', romaji: 'mizu', spanish: 'agua', jlpt: 'N5' },
        { kanji: '火', hiragana: 'ひ', romaji: 'hi', spanish: 'fuego', jlpt: 'N5' },
        { kanji: '木', hiragana: 'き', romaji: 'ki', spanish: 'árbol', jlpt: 'N5' },
        { kanji: '金', hiragana: 'きん', romaji: 'kin', spanish: 'oro', jlpt: 'N4' },
        { kanji: '愛', hiragana: 'あい', romaji: 'ai', spanish: 'amor', jlpt: 'N3' },
        { kanji: '日本人', hiragana: 'にほんじん', romaji: 'nihonjin', spanish: 'persona japonesa', jlpt: 'N5' }
    ],

    // Fechas
    fechas: {
        dias: [
            { japanese: '月曜日', hiragana: 'げつようび', romaji: 'getsuyoubi', spanish: 'lunes' },
            { japanese: '火曜日', hiragana: 'かようび', romaji: 'kayoubi', spanish: 'martes' },
            { japanese: '水曜日', hiragana: 'すいようび', romaji: 'suiyoubi', spanish: 'miércoles' },
            { japanese: '木曜日', hiragana: 'もくようび', romaji: 'mokuyoubi', spanish: 'jueves' },
            { japanese: '金曜日', hiragana: 'きんようび', romaji: 'kinyoubi', spanish: 'viernes' },
            { japanese: '土曜日', hiragana: 'どようび', romaji: 'doyoubi', spanish: 'sábado' },
            { japanese: '日曜日', hiragana: 'にちようび', romaji: 'nichiyougi', spanish: 'domingo' }
        ],
        
        meses: [
            { japanese: '一月', hiragana: 'いちがつ', romaji: 'ichigatsu', spanish: 'enero' },
            { japanese: '二月', hiragana: 'にがつ', romaji: 'nigatsu', spanish: 'febrero' },
            { japanese: '三月', hiragana: 'さんがつ', romaji: 'sangatsu', spanish: 'marzo' },
            { japanese: '四月', hiragana: 'しがつ', romaji: 'shigatsu', spanish: 'abril' },
            { japanese: '五月', hiragana: 'ごがつ', romaji: 'gogatsu', spanish: 'mayo' },
            { japanese: '六月', hiragana: 'ろくがつ', romaji: 'rokugatsu', spanish: 'junio' },
            { japanese: '七月', hiragana: 'しちがつ', romaji: 'shichigatsu', spanish: 'julio' },
            { japanese: '八月', hiragana: 'はちがつ', romaji: 'hachigatsu', spanish: 'agosto' },
            { japanese: '九月', hiragana: 'くがつ', romaji: 'kugatsu', spanish: 'septiembre' },
            { japanese: '十月', hiragana: 'じゅうがつ', romaji: 'juugatsu', spanish: 'octubre' },
            { japanese: '十一月', hiragana: 'じゅういちがつ', romaji: 'juuichigatsu', spanish: 'noviembre' },
            { japanese: '十二月', hiragana: 'じゅうにがつ', romaji: 'juunigatsu', spanish: 'diciembre' }
        ]
    },

    // Números
    numeros: [
        { japanese: '零', hiragana: 'れい', romaji: 'rei', spanish: '0' },
        { japanese: '一', hiragana: 'いち', romaji: 'ichi', spanish: '1' },
        { japanese: '二', hiragana: 'に', romaji: 'ni', spanish: '2' },
        { japanese: '三', hiragana: 'さん', romaji: 'san', spanish: '3' },
        { japanese: '四', hiragana: 'し/よん', romaji: 'shi/yon', spanish: '4' },
        { japanese: '五', hiragana: 'ご', romaji: 'go', spanish: '5' },
        { japanese: '六', hiragana: 'ろく', romaji: 'roku', spanish: '6' },
        { japanese: '七', hiragana: 'しち', romaji: 'shichi', spanish: '7' },
        { japanese: '八', hiragana: 'はち', romaji: 'hachi', spanish: '8' },
        { japanese: '九', hiragana: 'きゅう', romaji: 'kyuu', spanish: '9' },
        { japanese: '十', hiragana: 'じゅう', romaji: 'juu', spanish: '10' },
        { japanese: '百', hiragana: 'ひゃく', romaji: 'hyaku', spanish: '100' },
        { japanese: '千', hiragana: 'せん', romaji: 'sen', spanish: '1000' },
        { japanese: '一万', hiragana: 'いちまん', romaji: 'ichiman', spanish: '10000' }
    ],

    // Gramática JLPT
    gramatica: [
        { pattern: 'は', usage: 'marcador de tema', example: 'これはペンです (kore wa pen desu)', translation: 'esto es un bolígrafo', jlpt: 'N5' },
        { pattern: 'が', usage: 'marcador de tema específico', example: '私が学生です (watashi ga gakusei desu)', translation: 'soy estudiante', jlpt: 'N5' },
        { pattern: 'を', usage: 'objeto directo', example: 'ご飯を食べます (gohan o tabemasu)', translation: 'como comida', jlpt: 'N5' },
        { pattern: 'に', usage: 'tiempo/lugar/destino', example: '学校に行きます (gakkou ni ikimasu)', translation: 'voy a la escuela', jlpt: 'N5' },
        { pattern: 'で', usage: 'lugar de acción', example: '教室で勉強します (kyoushitsu de benkyou shimasu)', translation: 'estudio en el aula', jlpt: 'N5' },
        { pattern: 'と', usage: 'y/ampersand', example: '本とペン (hon to pen)', translation: 'libro y bolígrafo', jlpt: 'N5' },
        { pattern: 'へ', usage: 'dirección', example: '東京へ行きます (Tokyo e ikimasu)', translation: 'voy hacia Tokio', jlpt: 'N5' },
        { pattern: 'も', usage: 'también/incluso', example: '私も学生です (watashi mo gakusei desu)', translation: 'yo también soy estudiante', jlpt: 'N5' },
        { pattern: 'の', usage: 'posesión/apostrophe', example: '私の本 (watashi no hon)', translation: 'mi libro', jlpt: 'N5' },
        { pattern: 'から', usage: 'desde/causa', example: '日本から来ました (Nihon kara kimashita)', translation: 'vengo de Japón', jlpt: 'N5' },
        { pattern: 'まで', usage: 'hasta', example: '5時まで勉強します (goji made benkyou shimasu)', translation: 'estudio hasta las 5', jlpt: 'N5' },
        { pattern: 'より', usage: 'comparación que', example: 'AよりBのほうがいい (A yori B no hou ga ii)', translation: 'B es mejor que A', jlpt: 'N4' }
    ],

    // Utilidades
    utils: {
        shuffle: function(array) {
            const shuffled = [...array];
            for (let i = shuffled.length - 1; i > 0; i--) {
                const j = Math.floor(Math.random() * (i + 1));
                [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
            }
            return shuffled;
        },
        
        getRandomIndex: function(length) {
            return Math.floor(Math.random() * length);
        }
    }
};